version: "3.9"
services:
  db_encurtador:
    image: postgres:16
    container_name: db_encurtador
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: encurtador
    ports:
      - "5432:5432"
    volumes:
      - ./docker/postgres/data:/var/lib/postgresql/data
